### ISSUE TITLE
เสนอเปลี่ยนโครงสร้างเก็บนิยาย 

### ISSUE THREAD

**Issue by pureexe** [Richter03/gitboard#12]
การเก็บนิยาย โดยใช้  ` นิยาย/นามปากกาของท่าน/ชื่อเรื่อง.md` ดูแล้วกก็ปัญหาเยอะมาก เพราะถ้าเรื่องนึงไฟล์ยาวสัก 200 ตอนคนเปิดอ่านนี่โหลดเละแน่นอน เน็ตมือถือหมดโดยพลัน นอกจากนี้ยังมีปัญหาเปลี่ยนมือคนแปล มันจะกลายเป็น   ` นิยาย/คนแปล1/เรื่องA.md` กับ ` นิยาย/คนแปล2/เรื่องA.md` ที่แต่ละตอนมีไฟล์ไม่เหมือนกัน

จึงเสนอให้แก้ โครงสร้างเป็นดังนี้
` นิยาย/ชื่อเรื่อง (romanji หรือ pin-in หรือถอดเสียงจากชื่อเรื่องต้นฉบับ) / 0001 (เลขตอน 4 หลัก) .md `

สำหรับเรื่องการให้ credit ท่านสามารถใส่ชื่อคนแปลโดยใช้ หัวไฟล์ดังนี้ จะแสดงออกมาเป็นตาราง
```
---
translator: ชื่อ
---
```

**Comment by Richter03** [comment]
[`แปล`|`นิยายแปล`]/ชื่อเรื่อง (romanji หรือ pin-in หรือถอดเสียงจากชื่อเรื่องต้นฉบับ)/[`0001(เลขตอน 4 หลัก) - ชื่อตอน.md`|`(เล่มที่)01 - ชื่อประจำเล่มนิยายนั้นๆ(ถ้ามี)/001(เลขตอน 2 - 3 หลัก) - ชื่อตอน.md`]  

ไม่แน่ใจว่าถ้าผมใช้ `แปล` ฮ้วนๆ ไปเลยจะสั้นไปหรือปล่าวในการระบุกลุ่มว่าเป็นของนิยายแปล `นิยาย` เฉยๆ จะเป็นกลุ่มนิยายแต่งเอง เลขตอนผมเพิ่มแบบระบุเล่มไปด้วยเผื่อนิยายจีนหรือเกาหลีที่ยังไม่ lc
